export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const SEARCH_BOOKS_LOADING = 'SEARCH_BOOKS_LOADING';

export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE';
export const CLEAR_SEARCH_STATUS = 'CLEAR_SEARCH_STATUS';
