export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAILURE = 'FETCH_BOOK_FAILURE';
export const CLEAR_FETCH_STATUS = 'CLEAR_FETCH_STATUS';

export const UPDATE_RATINGS = 'UPDATE_RATINGS';
