export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOADING_USER = 'LOADING_USER';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT = 'SIGN_OUT';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';
export const CLEAR_EDIT_STATUS = 'CLEAR_EDIT_STATUS';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const PROFILE_WAS_UPDATED = 'PROFILE_WAS_UPDATED';

export const SENT_FRIEND_REQUEST = 'SENT_FRIEND_REQUEST';
export const CANCELED_FRIEND_REQUEST = 'CANCELED_FRIEND_REQUEST';
export const ACCEPTED_FRIEND_REQUEST = 'ACCEPTED_FRIEND_REQUEST';
export const IGNORED_FRIEND_REQUEST = 'IGNORED_FRIEND_REQUEST';

export const CLEAR_FAILED_SIGNUP = 'CLEAR_FAILED_SIGNUP';
export const CLEAR_FAILED_SIGNIN = 'CLEAR_FAILED_SIGNIN';
export const CLEAR_LANDING_AUTH_FAIL = 'CLEAR_LANDING_AUTH_FAIL';
