export const LOADING_PROFILE = 'LOADING_PROFILE';

export const PREPARE_LOAD_PROFILE = 'PREPARE_LOAD_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';
export const CLEAR_EDIT_STATUS = 'CLEAR_EDIT_STATUS';

export const EDIT_AVATAR_SUCCESS = 'EDIT_AVATAR_SUCCESS';
export const EDIT_AVATAR_FAILURE = 'EDIT_AVATAR_FAILURE';
export const CLEAR_EDIT_AVATAR_STATUS = 'CLEAR_EDIT_AVATAR_STATUS';

export const SHELVE_BOOK = 'SHELVE_BOOK';

export const SIGNAL_BOOK_WAS_RATED = 'SIGNAL_BOOK_WAS_RATED';
export const RESET_BOOK_WAS_RATED_SIGNAL = 'RESET_BOOK_WAS_RATED_SIGNAL';

// export const MARK_MESSAGE = 'MARK_MESSAGE';
// export const MARK_MESSAGE_FAILURE = 'MARK_MESSAGE_FAILURE';

// export const TRASH_MESSAGE = 'TRASH_MESSAGE';
// export const TRASH_MESSAGE_FAILURE = 'TRASH_MESSAGE_FAILURE';

// export const OPEN_NEW_MESSAGE = 'OPEN_NEW_MESSAGE';

// export const DELETE_MESSAGE = 'DELETE_MESSAGE';
// export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';

// export const UPDATE_MAILBOX = 'UPDATE_MAILBOX';
