export const PREPARE_LOAD_PROFILE = 'PREPARE_LOAD_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';
export const CLEAR_EDIT_STATUS = 'CLEAR_EDIT_STATUS';

export const EDIT_AVATAR_SUCCESS = 'EDIT_AVATAR_SUCCESS';
export const EDIT_AVATAR_FAILURE = 'EDIT_AVATAR_FAILURE';
export const CLEAR_EDIT_AVATAR_STATUS = 'CLEAR_EDIT_AVATAR_STATUS';

export const SHELVE_BOOK = 'SHELVE_BOOK';

export const SIGNAL_BOOK_WAS_RATED = 'SIGNAL_BOOK_WAS_RATED';
export const RESET_BOOK_WAS_RATED_SIGNAL = 'RESET_BOOK_WAS_RATED_SIGNAL';
