export const FETCH_INBOX = 'FETCH_INBOX';
export const FETCH_TRASH = 'FETCH_TRASH';
export const FETCH_SAVED = 'FETCH_SAVED';
export const FETCH_SENT = 'FETCH_SENT';
export const FETCH_SPOOL = 'FETCH_SPOOL';
export const FETCH_MAIL_FAILURE = 'FETCH_MAIL_FAILURE';

export const SEND_MAIL = 'SEND_MAIL';

export const MAIL_ACTION_SUCCESS = 'MAIL_ACTION_SUCCESS';
export const MAIL_ACTION_FAILURE = 'MAIL_ACTION_FAILURE';

export const UPDATE_MAILBOX = 'UPDATE_MAILBOX';
export const UPDATE_MAILBOX_FAILURE = 'UPDATE_MAILBOX_FAILURE';
export const CLEAR_MAIL_ACTION_STATUS = 'CLEAR_MAIL_ACTION_STATUS';
export const CLEAR_SPOOL = 'CLEAR_SPOOL';
