export const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS';
export const FETCH_AUTHOR_FAILURE = 'FETCH_AUTHOR_FAILURE';

export const FETCH_AUTHOR_BOOKS_SUCCESS = 'FETCH_AUTHOR_BOOKS_SUCCESS';
export const FETCH_AUTHOR_BOOKS_FAILURE = 'FETCH_AUTHOR_BOOKS_FAILURE';

export const CLEAR_FETCH_STATUS = 'CLEAR_FETCH_STATUS';
